# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de81db9644731f7e2b0002e8899a9973cf7c05493fb3808ee12e8616d35f138156c266d72bfe1a84860a09e941797d657755089f0d3edb3f253fbd7e73a84d6a

test:
  secret_key_base: babacf240738b114c8eabd6df93fa130e1f016e5b3187012866090c970537906287cc89a436a52fe1a401335d8e33b0ad92e27edcbeda62f146cc4400d321d91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
